---
- hosts: 127.0.0.1
  gather_facts: no
  become: no
  connection: local
  vars_files:
    - ./group_vars/all.yml
    - ./group_vars/{{ CONFIG }}.yml

  tasks:
    - name: Create build folder if does not exists
      file:
        path: "templates/build"
        state: directory
      tags:
        - always

    - name: configure event names
      include: playbooks/configure_event_names.yml


    - name: generate sns terraform
      template: src=templates/sns_topics.tf.j2
        dest=terraform/sns_topics.tf
      when:
        - CONFIG != "production"
        - GenerateSnsTopicsForTesting

    - name: generate sqs terraform
      template: src=templates/sqs_queues.tf.j2
        dest=terraform/sqs.tf

    - name: don't provision sns topics in production
      file: path=templates/terraform/simulator_sns.tf state=absent
      when:
        - CONFIG == "production"
        - not GenerateSnsTopicsForTesting

    - name: provision terraform
      include_role:
        name: ansible-terraform
      vars:
        terraform_path: "./terraform"
        terraform_state: "{{TERRAFORM_STATE}}"
        workspace: "{{STACK_NAME}}"

    - name: generate env
      template: src=templates/env_template.env.j2
        dest=templates/build/envs/env.env

