module "app" {
  source = "../terraform"
  BAR_QUEUE_NAME = var.BAR_QUEUE_NAME
  BAR_TOPIC_NAME = var.BAR_TOPIC_NAME
  DEFAULT_TAGS = var.DEFAULT_TAGS
  DYNAMODB_ENDPOINT = var.DYNAMODB_ENDPOINT
  EVENT_TABLE_NAME = var.EVENT_TABLE_NAME
  FOO_QUEUE_NAME = var.FOO_QUEUE_NAME
  FOO_TOPIC_NAME = var.FOO_TOPIC_NAME
  SNS_ENDPOINT = var.SNS_ENDPOINT
  SQS_ENDPOINT = var.SQS_ENDPOINT
  STS_ENDPOINT = var.STS_ENDPOINT
  TERRAFORM_ROLE_ARN = var.TERRAFORM_ROLE_ARN
}